### ISSUE TITLE
[TODO]: Testing all environments 

### ISSUE THREAD

**Issue by Eventyret** [Eventyret/Padawan#14]
All environments should work correctly.

- [ ] Test in Linux Environment
- [ ] Test in Mac Environment
- [ ] Test in Windows Environment
